In [1]:
import numpy as np

In [2]:
from numpy import array

In [4]:
fam = ["Sakib", 1.8, "Zarir", 1,77, "Imrul", 1.87]
fam

['Sakib', 1.8, 'Zarir', 1, 77, 'Imrul', 1.87]

In [6]:
fam_ext = fam + ["me", 1.85]
fam_ext

['Sakib', 1.8, 'Zarir', 1, 77, 'Imrul', 1.87, 'me', 1.85]

In [7]:
print(str(len(fam_ext)) + " elements in fam_ext")

9 elements in fam_ext


In [10]:
np_fam = np.array(fam_ext)

In [11]:
np_fam

array(['Sakib', '1.8', 'Zarir', '1', '77', 'Imrul', '1.87', 'me', '1.85'],
      dtype='<U32')

In [13]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
height


[1.73, 1.68, 1.71, 1.89, 1.79]

In [16]:
height_np = np.array(height)
height_np

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [14]:
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
weight

[65.4, 59.2, 63.6, 88.4, 68.7]

In [17]:
weight_np = np.array(weight)
weight_np

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [18]:
bmi = weight_np / height_np ** 2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [19]:
bmi > 23

array([False, False, False,  True, False])

In [20]:
bmi[ bmi > 23 ]

array([24.7473475])

# **2D numpy Arrays**

In [25]:
np_2d = np.array([[1.73, 1.87, 1.84, 1.70],
                  [63.2, 66.5, 64.3, 63.8]])
np_2d

array([[ 1.73,  1.87,  1.84,  1.7 ],
       [63.2 , 66.5 , 64.3 , 63.8 ]])

In [27]:
np_2d.shape

(2, 4)

In [28]:
type(np_2d)

numpy.ndarray

In [29]:
np_2d[0]

array([1.73, 1.87, 1.84, 1.7 ])

In [30]:
np_2d[0,1]

np.float64(1.87)

In [31]:
np_2d[:, 1:4]

array([[ 1.87,  1.84,  1.7 ],
       [66.5 , 64.3 , 63.8 ]])

In [38]:
np_2d[:, -2]

array([ 1.84, 64.3 ])

In [39]:
np.mean(np_2d[:, 0])

np.float64(32.465)

In [40]:
height1 = np.round(np.random.normal(1.75, 0.20, 100), 2)
weight1 = np.round(np.random.normal(60.32, 15, 100), 2)

In [42]:
np_city = np.column_stack((height1, weight1))

In [43]:
np_city

array([[ 1.77, 72.82],
       [ 1.79, 88.37],
       [ 1.73, 28.68],
       [ 1.86, 70.41],
       [ 1.46, 54.61],
       [ 1.37, 68.42],
       [ 1.86, 54.26],
       [ 1.69, 68.76],
       [ 1.91, 63.32],
       [ 1.47, 46.74],
       [ 1.87, 56.6 ],
       [ 1.55, 34.25],
       [ 1.54, 69.1 ],
       [ 1.7 , 41.01],
       [ 1.9 , 56.68],
       [ 1.78, 35.81],
       [ 1.59, 71.84],
       [ 1.83, 40.22],
       [ 1.68, 72.81],
       [ 1.81, 56.38],
       [ 1.93, 60.66],
       [ 1.82, 68.57],
       [ 1.85, 54.58],
       [ 1.52, 50.74],
       [ 1.75, 67.38],
       [ 1.87, 50.27],
       [ 1.6 , 59.78],
       [ 1.84, 47.55],
       [ 1.91, 54.09],
       [ 1.86, 79.27],
       [ 1.77, 59.47],
       [ 1.98, 83.05],
       [ 1.93, 39.74],
       [ 1.6 , 62.69],
       [ 1.77, 77.78],
       [ 1.88, 41.39],
       [ 1.56, 72.66],
       [ 1.64, 52.3 ],
       [ 1.55, 43.42],
       [ 1.68, 46.42],
       [ 1.88, 82.12],
       [ 1.74, 64.05],
       [ 1.64, 53.06],
       [ 2.