In [5]:
import numpy as np
import pandas as pd

In [15]:
list1 = [1, 2, 3, 4]

In [16]:
print(list1)

[1, 2, 3, 4]


In [17]:
# convert list to array

np_list1 = np.array(list1)

In [18]:
print(np_list1)

[1 2 3 4]


#Height and Weight in list

In [24]:
height = [74, 74, 72, 72, 73]
weight = [180, 215, 210, 210, 188]

In [29]:
type(height)

list

In [25]:
# convert to array

np_height = np.array(height)
np_weight = np.array(weight)

In [26]:
np_height

array([74, 74, 72, 72, 73])

In [27]:
np_weight

array([180, 215, 210, 210, 188])

In [28]:
type(np_weight)

numpy.ndarray

In [32]:
#calculate bmi

bmi = np_weight / np_height ** 2

In [33]:
bmi

array([0.03287071, 0.03926224, 0.04050926, 0.04050926, 0.03527866])

In [34]:
bmi[1]

np.float64(0.03926223520818115)

In [35]:
bmi > 23

array([False, False, False, False, False])

**2D Array**

In [38]:
np_2d = np.array([height, weight])

In [39]:
np_2d

array([[ 74,  74,  72,  72,  73],
       [180, 215, 210, 210, 188]])

In [40]:
np_2d[0]

array([74, 74, 72, 72, 73])

In [42]:
np_2d[0, 2]

np.int64(72)

In [43]:
np_2d[:, 1:3]

array([[ 74,  72],
       [215, 210]])

**Create random height and weight**

In [48]:
height_rand = np.round(np.random.normal(1.75, 0.20, 5000), 2)

In [49]:
height_rand

array([1.87, 1.93, 1.68, ..., 1.96, 1.94, 1.71])

In [6]:
baseball = pd.read_csv("https://assets.datacamp.com/production/repositories/288/datasets/e5d60ff535f86d27609312f9e41c35a1d737ddc0/baseball.csv")

In [7]:
print(baseball)

                 Name Team        Position  Height  Weight    Age PosCategory
0       Adam_Donachie  BAL         Catcher      74     180  22.99     Catcher
1           Paul_Bako  BAL         Catcher      74     215  34.69     Catcher
2     Ramon_Hernandez  BAL         Catcher      72     210  30.78     Catcher
3        Kevin_Millar  BAL   First_Baseman      72     210  35.43   Infielder
4         Chris_Gomez  BAL   First_Baseman      73     188  35.71   Infielder
...               ...  ...             ...     ...     ...    ...         ...
1010    Brad_Thompson  STL  Relief_Pitcher      73     190  25.08     Pitcher
1011    Tyler_Johnson  STL  Relief_Pitcher      74     180  25.73     Pitcher
1012   Chris_Narveson  STL  Relief_Pitcher      75     205  25.19     Pitcher
1013    Randy_Keisler  STL  Relief_Pitcher      75     190  31.01     Pitcher
1014      Josh_Kinney  STL  Relief_Pitcher      73     195  27.92     Pitcher

[1015 rows x 7 columns]


In [30]:
type(baseball)

pandas.core.frame.DataFrame

In [21]:
np_baseball_height = np.array(baseball.iloc[:, 3])

In [22]:
print(np_baseball_height)

[74 74 72 ... 75 75 73]


In [45]:
np_baseball_weight = np.array(baseball.iloc[:, 4])

In [46]:
np_baseball_weight

array([180, 215, 210, ..., 205, 190, 195])